### ISSUE TITLE
Rückschluss zu Wahlverhalten nach Geschlecht

### ISSUE THREAD

**Issue by ccauet** [CodeforKarlsruhe/btw2017-stadtteile#2]
Hallo und vielen Dank für die schöne Visualisierung! 

Über die getroffene Aussage des Wahlverhaltens der Frauen in den Karlsruher Stadtteilen muss man aber glaube ich nochmal diskutieren.

> In den Stadtteilen mit hohem Frauenanteil unter den Einwohnern haben tendenziell CDU und AfD die Nase vorn.

Das stimmt so nicht. Es ändert sich die Reihenfolge des Parteienrankings von links (42% Frauenanteil): AFD, FDP, Linke, SPD, CDU, Grüne zu rechts (>52% Frauenanteil): Linke, FDP, AFD, Grüne, SPD, CDU. Aber auch bei den Stadtteilen mit vielen Wählerinnen dominieren CDU, SPD und Grüne.

> Auch bundesweit haben Frauen verstärkt CDU gewählt, die AfD hingegen bekam deutschlandweit ihre Stimmen eher von den Männern. Klare Verlierer bei den Karlsruher Frauen sind die Grünen und die Linke.

Hierzu wäre sehr interessant wie sich der Frauenanteil zum Durchschnittsalter in den Stadtteilen  verhält. Aus dem Bauch raus würde ich vermuten: Stark technische-ingenieurwissenschaftlich dominierte Universität mit geringerem Frauenanteil macht sich in den studentisch geprägten Stadtteilen bemerkbar --> Stadtteile mit weniger Wählerinnen == Stadtteile mit jüngeren Bewohnern.

Mich würde daher grundsätzlich (auch für die erste getroffene Aussage) interessieren wie Frauenanteil zu Durchschnittsalter korreliert.

**Comment by hcorinna** [comment]
Hallo Christophe,

sehr guter Punkt, vielen Dank für den Hinweis.

> Über die getroffene Aussage des Wahlverhaltens der Frauen in den Karlsruher Stadtteilen muss man aber glaube ich nochmal diskutieren. [...] [Auch] bei den Stadtteilen mit vielen Wählerinnen dominieren CDU, SPD und Grüne.

Du hast natürlich vollkommen recht. Die Aussage darüber, dass CDU und AfD die Nase vorn hätten, ist aktuell missverständlich und wird von uns klar gestellt. Ich würde sowas wie "In den Stadtteilen mit hohem Frauenanteil unter den Einwohnern werden tendenziell häufiger CDU und AfD gewählt als in solchen mit niedrigerem Frauenanteil" vorschlagen, wobei das natürlich im Hinblick auf die vermutete Korrelation von Durchnittsalter und Frauenanteil nach wie vor irreführend ist.

> Hierzu wäre sehr interessant wie sich der Frauenanteil zum Durchschnittsalter in den Stadtteilen verhält.

Wenn man sich die Stadtteile mit dem geringeren Frauenanteil anschaut, liegen diese in der Innenstadt, wo vermutlich tendenziell wie von dir angemerkt die überwiegend männlichen Studenten leben. Um die Vermutung zu bestätigen, habe ich [die Korrelation mal geplottet](https://jsfiddle.net/hcorinna/0eav3w3a/). Da ein höherer Anteil junger Menschen tatsächlich mit einem niedrigeren Frauenanteil einhergeht, sollten wir die Korrelation auf jeden Fall in die Auswertung einbringen, da der Rückschluss vom Geschlecht auf das Wahlverhalten anderfalls irreführend ist.

**Comment by ccauet** [comment]
> Ich würde sowas wie "In den Stadtteilen mit hohem Frauenanteil unter den Einwohnern werden tendenziell häufiger CDU und AfD gewählt als in solchen mit niedrigerem Frauenanteil" vorschlagen, wobei das natürlich im Hinblick auf die vermutete Korrelation von Durchnittsalter und Frauenanteil nach wie vor irreführend ist.

Ja, die Aussage passt besser.

> Da ein höherer Anteil junger Menschen tatsächlich mit einem niedrigeren Frauenanteil einhergeht, sollten wir die Korrelation auf jeden Fall in die Auswertung einbringen, da der Rückschluss vom Geschlecht auf das Wahlverhalten anderfalls irreführend ist.

Ein Hinweissatz wäre ja erstmal ausreichend. Letztendlich bleibt es ja eine eindimensionale Darstellung.

Irgendwie habe ich jetzt erst entdeckt, dass es bereits noch mehr Dimensionen gibt. Das gucke ich mir nochmal in Ruhe an.

**Comment by hcorinna** [comment]
Die Analyse habe ich jetzt überarbeitet, aber Verbesserungsvorschläge sind natürlich sehr willkommen.
Schau dir gern noch die Dimensionen an, ich bin gespannt auf die neuen Erkenntnisse :)

**Comment by torfsen** [comment]
Vielen Dank, @ccauet, für Dein Feedback! Die Kritik am ursprünglichen Text war berechtigt, @hcorinna hat das ja mittlerweile korrigiert. Dass Du die weiteren Analysen erst später gefunden hast habe ich zum Anlass genommen, dem "Weiter"-Button anfangs noch ein pulsierendes Aussehen zu geben um auf ihn aufmerksam zu machen.

Was Deine Analyse angeht: Das sind auf jeden Fall interessante Fragen! Es gibt in den Karlsruher Stadtteilen in der Tat eine Korrelation zwischen dem Anteil von Menschen unter 25 und dem Frauenanteil:

![frauen-jugend](https://user-images.githubusercontent.com/2877717/31790627-633ce5ca-b516-11e7-9371-6bbf0d17a703.png)

Allerdings sieht man ja bei unseren Diagrammen zu Jugend- und Seniorenanteil, dass der Zusammenhang zwischen Alter und Wahlergebnis komplexer ist als man vielleicht denkt (die "alten" Stadtteile haben z.B. nicht überproportional konservativ gewählt).

Solche tiefgreifenden Analysen wären auf jeden Fall eine Bereicherung für das Projekt, allerdings müsste man das erstens statistisch sauber aufziehen und zweitens möglichst für alle Diagramme machen (oder eine gemeinsame Analyse die auf alles eingeht) -- von daher habe ich die Einzelanalyse von @hcorinna auch mal wieder rausgenommen. Wenn jemand Zeit hat das umfassend zu machen dann freuen wir uns über einen PR.

Ich mache die Issue mal zu, falls noch Punkte offen sind gerne wieder aufmachen.
